### ISSUE TITLE
An unexpected error occurred: "Something broke when publishing... "

### ISSUE THREAD

**Issue by halvardssm** [nestdotland/eggs#101]
## 🐛 Bug Report

[CRIT] An unexpected error occurred: "Something broke when publishing... "

## To Reproduce
1. Use config from debug log

2. Link you api key

```
deno run -A --unstable https://x.nest.land/eggs@0.3.0/eggs.ts link <api_key>
```

3. Publish

```
deno run -A --unstable https://x.nest.land/eggs@0.3.0/eggs.ts publish
```

## Expected behavior

Expected the package to publish

## Actual Behavior

```
[CRIT] An unexpected error occurred: "Something broke when publishing... " "Error: Something broke when publishing... \n    at Command.publish [as fn] (publish.ts:365:11)\n    at async Command.execute (command.ts:796:9)\n    at async Command.parse (command.ts:731:14)\n    at async Command.parse (command.ts:688:14)\n    at async eggs.ts:74:23"
```

## Environment

- Eggs version: 0.3.0
- Deno version: 1.4.6
- Operating system and version: MacOS Catalina 10.15.7

## Additional context

```
Arguments:
  publish

Deno version:
  deno: 1.4.6
  v8: 8.7.220.3
  typescript: 4.0.3

Eggs version:
  0.3.0

Platform:
  x86_64-apple-darwin

2020-10-25T09:53:20.988Z [DEBUG]    Raw config: {
  name: "Oak Middleware JWT",
  entry: "./mod.ts",
  description: "Oak middleware for JWT validation using djwt",
  homepage: "https://github.com/halvardssm/oak-middleware-jwt",
  version: "1.0.0",
  files: [ "./mod.ts", "./deps.ts", "./src/**/*", "./README.md", "./LICENSE" ],
  checkFormat: false,
  checkTests: false,
  checkInstallation: false,
  check: true
}
2020-10-25T09:53:20.990Z [DEBUG]    Ignore: undefined
2020-10-25T09:53:21.002Z [DEBUG]    Matched files: [
  {
    fullPath: "/oak-middleware-jwt/mod.ts",
    path: "/mod.ts",
    lstat: {
      isFile: true,
      isDirectory: false,
      isSymlink: false,
      size: 40,
      mtime: 2020-06-02T09:30:10.671Z,
      atime: 2020-06-02T09:30:11.009Z,
      birthtime: 2020-05-25T18:26:58.027Z,
      dev: 16777223,
      ino: 86321710,
      mode: 33188,
      nlink: 1,
      uid: 501,
      gid: 20,
      rdev: 0,
      blksize: 4096,
      blocks: 8
    }
  },
  {
    fullPath: "/oak-middleware-jwt/mod.ts",
    path: "/mod.ts",
    lstat: {
      isFile: true,
      isDirectory: false,
      isSymlink: false,
      size: 40,
      mtime: 2020-06-02T09:30:10.671Z,
      atime: 2020-06-02T09:30:11.009Z,
      birthtime: 2020-05-25T18:26:58.027Z,
      dev: 16777223,
      ino: 86321710,
      mode: 33188,
      nlink: 1,
      uid: 501,
      gid: 20,
      rdev: 0,
      blksize: 4096,
      blocks: 8
    }
  },
  {
    fullPath: "/oak-middleware-jwt/deps.ts",
    path: "/deps.ts",
    lstat: {
      isFile: true,
      isDirectory: false,
      isSymlink: false,
      size: 560,
      mtime: 2020-10-25T09:45:53.352Z,
      atime: 2020-10-25T09:45:53.427Z,
      birthtime: 2020-08-30T17:45:20.483Z,
      dev: 16777223,
      ino: 109401815,
      mode: 33188,
      nlink: 1,
      uid: 501,
      gid: 20,
      rdev: 0,
      blksize: 4096,
      blocks: 8
    }
  },
  {
    fullPath: "/oak-middleware-jwt/src/jwtMiddleware.ts",
    path: "/src/jwtMiddleware.ts",
    lstat: {
      isFile: true,
      isDirectory: false,
      isSymlink: false,
      size: 3855,
      mtime: 2020-10-25T09:08:47.354Z,
      atime: 2020-10-25T09:09:13.010Z,
      birthtime: 2020-08-30T17:45:20.484Z,
      dev: 16777223,
      ino: 109401816,
      mode: 33188,
      nlink: 1,
      uid: 501,
      gid: 20,
      rdev: 0,
      blksize: 4096,
      blocks: 8
    }
  },
  {
    fullPath: "/oak-middleware-jwt/README.md",
    path: "/README.md",
    lstat: {
      isFile: true,
      isDirectory: false,
      isSymlink: false,
      size: 3581,
      mtime: 2020-10-25T09:36:40.299Z,
      atime: 2020-10-25T09:36:41.803Z,
      birthtime: 2020-08-30T17:45:20.483Z,
      dev: 16777223,
      ino: 109401814,
      mode: 33188,
      nlink: 1,
      uid: 501,
      gid: 20,
      rdev: 0,
      blksize: 4096,
      blocks: 8
    }
  },
  {
    fullPath: "/oak-middleware-jwt/LICENSE",
    path: "/LICENSE",
    lstat: {
      isFile: true,
      isDirectory: false,
      isSymlink: false,
      size: 1077,
      mtime: 2020-05-25T09:39:54.562Z,
      atime: 2020-05-25T13:40:41.231Z,
      birthtime: 2020-05-25T09:39:54.561Z,
      dev: 16777223,
      ino: 86240260,
      mode: 33188,
      nlink: 1,
      uid: 501,
      gid: 20,
      rdev: 0,
      blksize: 4096,
      blocks: 8
    }
  }
]
2020-10-25T09:53:21.004Z [DEBUG]    Config: {
  name: "Oak Middleware JWT",
  entry: "/mod.ts",
  description: "Oak middleware for JWT validation using djwt",
  homepage: "https://github.com/halvardssm/oak-middleware-jwt",
  version: "1.0.0",
  files: [ "./mod.ts", "./deps.ts", "./src/**/*", "./README.md", "./LICENSE" ],
  checkFormat: false,
  checkTests: false,
  checkInstallation: false,
  check: true,
  ignore: [],
  unlisted: false
}
2020-10-25T09:53:21.905Z [INFO]     The resulting module is: 
        - name: "Oak Middleware JWT",
        - version: "1.0.0",
        - description: "Oak middleware for JWT validation using djwt",
        - repository: "https://github.com/halvardssm/oak-middleware-jwt",
        - unlisted: false,
        - stable: false,
        - upload: true,
        - latest: true,
        - entry: "/mod.ts"
2020-10-25T09:53:21.905Z [INFO]     Files to publish:
        - /mod.ts  (0.00004MB)
        - /mod.ts  (0.00004MB)
        - /deps.ts  (0.00056MB)
        - /src/jwtMiddleware.ts  (0.003855MB)
        - /README.md  (0.003581MB)
        - /LICENSE  (0.001077MB)
2020-10-25T09:53:24.573Z [CRITICAL] An unexpected error occurred: "Something broke when publishing... " "Error: Something broke when publishing... \n    at Command.publish [as fn] (publish.ts:365:11)\n    at async Command.execute (command.ts:796:9)\n    at async Command.parse (command.ts:731:14)\n    at async Command.parse (command.ts:688:14)\n    at async eggs.ts:74:23"
```

**Comment by littledivy** [comment]
The module name cannot have white spaces. Although the error message should be more descriptive.

**Comment by halvardssm** [comment]
I see. Thanks for your help!
