### ISSUE TITLE
 Property 'prompts' is used before its initialization.

### ISSUE THREAD

**Issue by v1rtl** [nestdotland/eggs#120]
## 🐛 Bug Report

Whenever I run `eggs` command I get this:

```
error: TS2729 [ERROR]: Property 'prompts' is used before its initialization.
  private names: string[] = this.prompts.map((prompt) => prompt.name);
                                 ~~~~~~~
    at https://xqalpbanzpdlq4nxt35ywjwpm6xwayfdny3pnikd4cp2ozmyl3xa.arweave.net/vAC3hA3Lxrhxt577iybPZ69gYKNuNvahQ-Cfp2WYXu4/prompt/prompt.ts:2010:34

    'prompts' is declared here.
        private prompts: PromptOptions<string, any, any>[],
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        at https://xqalpbanzpdlq4nxt35ywjwpm6xwayfdny3pnikd4cp2ozmyl3xa.arweave.net/vAC3hA3Lxrhxt577iybPZ69gYKNuNvahQ-Cfp2WYXu4/prompt/prompt.ts:2018:5

~ via ⬢ v15.12.0 via 🐍 v3.9.2 
➜ eggs update
error: TS2729 [ERROR]: Property 'prompts' is used before its initialization.
  private names: string[] = this.prompts.map((prompt) => prompt.name);
                                 ~~~~~~~
    at https://xqalpbanzpdlq4nxt35ywjwpm6xwayfdny3pnikd4cp2ozmyl3xa.arweave.net/vAC3hA3Lxrhxt577iybPZ69gYKNuNvahQ-Cfp2WYXu4/prompt/prompt.ts:2010:34

    'prompts' is declared here.
        private prompts: PromptOptions<string, any, any>[],
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        at https://xqalpbanzpdlq4nxt35ywjwpm6xwayfdny3pnikd4cp2ozmyl3xa.arweave.net/vAC3hA3Lxrhxt577iybPZ69gYKNuNvahQ-Cfp2WYXu4/prompt/prompt.ts:2018:5

~ via ⬢ v15.12.0 via 🐍 v3.9.2 
➜ eggs --help
error: TS2729 [ERROR]: Property 'prompts' is used before its initialization.
  private names: string[] = this.prompts.map((prompt) => prompt.name);
                                 ~~~~~~~
    at https://xqalpbanzpdlq4nxt35ywjwpm6xwayfdny3pnikd4cp2ozmyl3xa.arweave.net/vAC3hA3Lxrhxt577iybPZ69gYKNuNvahQ-Cfp2WYXu4/prompt/prompt.ts:2010:34

    'prompts' is declared here.
        private prompts: PromptOptions<string, any, any>[],
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        at https://xqalpbanzpdlq4nxt35ywjwpm6xwayfdny3pnikd4cp2ozmyl3xa.arweave.net/vAC3hA3Lxrhxt577iybPZ69gYKNuNvahQ-Cfp2WYXu4/prompt/prompt.ts:2018:5
```

## To Reproduce

1. Install Deno 1.9
2. Try to run `eggs`

## Expected behavior

Work as usual.

## Actual Behavior

It doesn't work, see error above.

## Environment

- Eggs version: 3.0.5
- Deno version: 1.9.0
- Operating system and version: Manjaro Linux x64

## Additional context

Probably with the new minor Deno update it broke

**Comment by maximousblk** [comment]
*sigh* looks like cliffy again...

@talentlessguy thanks for reporting this, can you bring this up on [our discord server](https://discord.gg/hYUsX3H) so we can take a closer look at this? 

PS: I think you meant eggs version 0.3.5?

**Comment by maximousblk** [comment]
@talentlessguy can you check if this issue still exists in eggs@0.3.6?

Install:
```sh
deno install -Afq --unstable https://x.nest.land/eggs@0.3.6/eggs.ts
```

**Comment by v1rtl** [comment]
@maximousblk now it works! thanks for resolving it very quickly
