### ISSUE TITLE
publish with --bump arg does not seem to work properly

### ISSUE THREAD

**Issue by zabihexes** [nestdotland/eggs#128]
Logs
```
Arguments:
  publish,--bump,patch

Deno version:
  deno: 1.11.0
  v8: 9.1.269.35
  typescript: 4.3.2

Eggs version:
  0.3.8

Platform:
  x86_64-pc-windows-msvc

2021-06-18T19:06:50.318Z [CRITICAL] An unexpected error occurred: "Unknown option "--bump". Did you mean option "--help"?" 'Error: Unknown option "--bump". Did you mean option "--help"?\n    at Command.parseFlags (https://ibbufvhlsot4bpfiwkap5xu6xxqsxqu6zbmefonuat3gvizgubrq.arweave.net/QENC1OuTp8C8qLKA_t6eveErwp7IWEK5tAT2aqMmoGM/command/command.ts:1124:15)\n    at Command.parse (https://ibbufvhlsot4bpfiwkap5xu6xxqsxqu6zbmefonuat3gvizgubrq.arweave.net/QENC1OuTp8C8qLKA_t6eveErwp7IWEK5tAT2aqMmoGM/command/command.ts:896:58)\n    at Command.parse (https://ibbufvhlsot4bpfiwkap5xu6xxqsxqu6zbmefonuat3gvizgubrq.arweave.net/QENC1OuTp8C8qLKA_t6eveErwp7IWEK5tAT2aqMmoGM/command/command.ts:870:33)\n    at https://7sp22f4di5uth6plorsiiumz67w2wofptwseuinyldrk5jrc5xta.arweave.net/_J-tF4NHaTP563RkhFGZ9-2rOK-dpEohuFjirqYi7eY/eggs.ts:74:34'
```
It should work fine according to [docs](https://docs.nest.land/eggs/publishing-a-module#options).

**Comment by zabihexes** [comment]
nvm, figured it out. Sorry
