### ISSUE TITLE
Error install in Deno 1.14

### ISSUE THREAD

**Issue by herudi** [nestdotland/eggs#132]
eggs the great tool. but i'm try to install `deno install -Af --unstable https://x.nest.land/eggs@0.3.8/eggs.ts` and getting error :
```bash
error: TS2801 [ERROR]: This condition will always return true since this 'Promise<Deno.PermissionStatus>' is always defined.
  if (Deno.permissions.query({ name: "env" })) {
      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://deno.land/x/tty@0.1.2/is_interactive.ts:2:7

TS2773 [ERROR]:     Did you forget to use 'await'?
      if (Deno.permissions.query({ name: "env" })) {
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        at https://deno.land/x/tty@0.1.2/is_interactive.ts:2:7
```

Deno: 1.14
eggs: 0.3.8

Thanks...

**Comment by maximousblk** [comment]
This should be fixed by #131

**Comment by maximousblk** [comment]
@herudi can you try again with https://github.com/nestdotland/eggs/releases/tag/0.3.9 ?

**Comment by herudi** [comment]
@maximousblk it's work. thanks
