### ISSUE TITLE
version 0.3.10 not installable

### ISSUE THREAD

**Issue by nnmrts** [nestdotland/eggs#136]
## 🐛 Bug Report

Running

```sh
deno install -Afq --unstable -n eggs https://x.nest.land/eggs@0.3.10/eggs.ts
```
throws this error:

```sh
error: Emitted code for "https://x.nest.land/eggs@0.3.10/eggs.ts" not found.
```

## To Reproduce

1. Run this:

```sh
deno install -Afq --unstable -n eggs https://x.nest.land/eggs@0.3.10/eggs.ts
```

## Expected behavior

It should install the latest version.

## Actual Behavior

It doesn't install the latest version, but instead throws an error.

## Environment

- Eggs version: 0.3.9
- Deno version: 1.16.1
- Operating system and version: macOS Montery beta 12.1 (21C5039b)

## Additional context

Running

```sh
eggs upgrade
```
throws with this:

```sh
[CRIT] An unexpected error occurred: "Failed to upgrade to the latest CLI version!"
[INFO] Debug file created. (/Users/nnmrts/eggs-debug.log)
[INFO] If you think this is a bug, please open a bug report at https://github.com/nestdotland/eggs/issues/new/choose with the information provided in /Users/nnmrts/eggs-debug.log
[INFO] Visit https://docs.nest.land/eggs/ for documentation about this command.
```

This is the content of `eggs-debug.log`:

```
Arguments:
  upgrade

Deno version:
  deno: 1.16.1
  v8: 9.7.106.2
  typescript: 4.4.2

Eggs version:
  0.3.9

Platform:
  x86_64-apple-darwin

2021-11-26T01:25:21.345Z [DEBUG]    stdout:  ""
2021-11-26T01:25:21.347Z [DEBUG]    stderr:  '\x1b[0m\x1b[1m\x1b[31merror\x1b[0m: Emitted code for "https://x.nest.land/eggs@0.3.10/eggs.ts" not found.\n'
2021-11-26T01:25:21.353Z [CRITICAL] An unexpected error occurred: "Failed to upgrade to the latest CLI version!" "Error: Failed to upgrade to the latest CLI version!
    at Command.upgrade [as fn] (https://jzyko3slwfqdzjdsou33pfterimczldnatkgr5gbecmatum3y3yq.arweave.net/TnCnbkuxYDykcnU3t5ZkihgsrG0E1Gj0wSCYCdGbxvE/src/commands/upgrade.ts:44:11)
    at async Command.execute (https://jwhfb66f7jdbrh5zp6sooj57qz2ur7p3n4uipb3cs5s2tdpndy6q.arweave.net/TY5Q-8X6RhifuX-k5ye_hnVI_ftvKIeHYpdlqY3tHj0/command/command.ts:993:7)
    at async Command.parse (https://jwhfb66f7jdbrh5zp6sooj57qz2ur7p3n4uipb3cs5s2tdpndy6q.arweave.net/TY5Q-8X6RhifuX-k5ye_hnVI_ftvKIeHYpdlqY3tHj0/command/command.ts:914:16)
    at async https://jzyko3slwfqdzjdsou33pfterimczldnatkgr5gbecmatum3y3yq.arweave.net/TnCnbkuxYDykcnU3t5ZkihgsrG0E1Gj0wSCYCdGbxvE/eggs.ts:74:23"
```

**Comment by nnmrts** [comment]
Btw, running the same thing with 0.3.9 like this:

```sh
deno install -Afq --unstable -n eggs https://x.nest.land/eggs@0.3.10/eggs.ts
```

does work as expected and installs eggs. So doesn't seem to be an issue with my system.

**Comment by nnmrts** [comment]
And since the actual source code of eggs between these two versions didn't change a lot, I suspect there was some form of breaking change in the dependencies that got updated.

**Comment by nnmrts** [comment]
Upgrading deno from 1.16.1 to 1.16.3 fixed the issue...
