### ISSUE TITLE
[BUG] Something broke when publishing... 

### ISSUE THREAD

**Issue by michael-spengler** [nestdotland/eggs#67]
First of all: Thank You for what you are doing - I think it's amazing. 

I wanted to publish a module and got the following eggs-debug.log which I could not interpret by myself to an extent that I could fix the error :) 

So perhaps you could automatically add a hint on what went wrong so that the publisher knows how to fix it.

Arguments:
  publish

Deno version:
  deno: 1.2.0
  v8: 8.5.216
  typescript: 3.9.2

Eggs version:
  0.2.1

Platform:
  x86_64-apple-darwin

2020-09-07T12:34:50.913Z [DEBUG]    Config:  {
  name: "log",
  description: "Frequently used logger configuration - writing warnings and errors into a file, adding date and time...",
  stable: true,
  files: [
    "logger.ts",
    "mod.ts",
    "README.md",
    "usage-example-sub-module.ts",
    "usage-example.ts"
  ]
}
2020-09-07T12:34:50.916Z [WARNING]  Your readme contains old import URLs from your project using deno.land/x/log.
2020-09-07T12:34:50.916Z [WARNING]  You can change these to https://x.nest.land/${name}@VERSION
2020-09-07T12:34:51.699Z [WARNING]  No version found. Generating a new version now...
2020-09-07T12:34:51.700Z [DEBUG]    Module:  {
  name: "log",
  description: "Frequently used logger configuration - writing warnings and errors into a file, adding date and time...",
  repository: undefined,
  version: "0.0.1",
  unlisted: undefined,
  upload: true,
  latest: true
}
2020-09-07T12:34:52.469Z [CRITICAL] An unexpected error occurred: "Something broke when publishing... " Error: Something broke when publishing... 
    at Command.publishCommand [as fn] (publish.ts:255:11)
    at async Command.execute (command.ts:666:17)
    at async Command.parse (command.ts:603:20)
    at async Command.parse (command.ts:570:20)
    at async mod.ts:47:23

**Comment by divy-work** [comment]
@michael-spengler Thank you for reporting this. This could probably be the API unexpectedly closing the connection with the CLI, could you try running the `publish` command again?

**Comment by littledivy** [comment]
@michael-spengler The name `log` is reserved as per https://github.com/nestdotland/x/blob/c94add3607c9fb7b45ac916d5f0776eb0fc0aeb1/src/utils/reservedNames.ts#L16
because of the std module `log`

**Comment by SteelAlloy** [comment]
> 
> 
> @michael-spengler The name `log` is reserved as per https://github.com/nestdotland/x/blob/c94add3607c9fb7b45ac916d5f0776eb0fc0aeb1/src/utils/reservedNames.ts#L16
> because of the std module `log`

That's right, it works as expected 😉
