### ISSUE TITLE
All eggs commands don't work in Deno 1.4

### ISSUE THREAD

**Issue by mjrlowe** [nestdotland/eggs#71]
**Describe the bug**
Whenever I run a command such as `eggs publish`, `eggs init` or `eggs -V` nothing happens. 
Previously (just after updating Deno to 1.4.0), I got the following error messages:
```
error: TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
export { LogLevels, LevelName } from "./levels.ts";
                    ~~~~~~~~~
    at https://iigk45i7o35wcqut6db5ji5nuwoj2nhlbqvk2jqrlhewcix6b7ja.arweave.net/QgyudR92-2FCk_DD1KOtpZydNOsMKq0mEVnJYSL-D9I/log/mod.ts:13:21

TS1371 [ERROR]: This import is never used as a value and must use 'import type' because the 'importsNotUsedAsValues' is set to 'error'.
import { LanguageSpecific } from 'https://deno.land/x/case/types.ts';
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://owhnahgrxgphnvioxm36tgjvmmia36lerfcwf2tj5pafdlfbe2na.arweave.net/dY7QHNG5nnbVDrs36Zk1YxAN-WSJRWLqaevAUayhJpo/packages/x/lowerCase.ts:5:1

TS1371 [ERROR]: This import is never used as a value and must use 'import type' because the 'importsNotUsedAsValues' is set to 'error'.
import { LanguageSpecific } from 'https://deno.land/x/case/types.ts';
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://owhnahgrxgphnvioxm36tgjvmmia36lerfcwf2tj5pafdlfbe2na.arweave.net/dY7QHNG5nnbVDrs36Zk1YxAN-WSJRWLqaevAUayhJpo/packages/x/upperCase.ts:1:1

TS1371 [ERROR]: This import is never used as a value and must use 'import type' because the 'importsNotUsedAsValues' is set to 'error'.
import { IFlagArgument, IFlagOptions, ITypeHandler } from '../types.ts';
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://owhnahgrxgphnvioxm36tgjvmmia36lerfcwf2tj5pafdlfbe2na.arweave.net/dY7QHNG5nnbVDrs36Zk1YxAN-WSJRWLqaevAUayhJpo/packages/flags/lib/types/boolean.ts:1:1

TS1371 [ERROR]: This import is never used as a value and must use 'import type' because the 'importsNotUsedAsValues' is set to 'error'.
import { IFlagArgument, IFlagOptions, ITypeHandler } from '../types.ts';
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://owhnahgrxgphnvioxm36tgjvmmia36lerfcwf2tj5pafdlfbe2na.arweave.net/dY7QHNG5nnbVDrs36Zk1YxAN-WSJRWLqaevAUayhJpo/packages/flags/lib/types/number.ts:1:1       

TS1371 [ERROR]: This import is never used as a value and must use 'import type' because the 'importsNotUsedAsValues' is set to 'error'.
import { IFlagArgument, IFlagOptions, ITypeHandler } from '../types.ts';
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://owhnahgrxgphnvioxm36tgjvmmia36lerfcwf2tj5pafdlfbe2na.arweave.net/dY7QHNG5nnbVDrs36Zk1YxAN-WSJRWLqaevAUayhJpo/packages/flags/lib/types/string.ts:1:1       

TS1371 [ERROR]: This import is never used as a value and must use 'import type' because the 'importsNotUsedAsValues' is set to 'error'.
import { IFlagArgument, IFlagOptions, IFlags, IFlagValue } from './types.ts';
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://owhnahgrxgphnvioxm36tgjvmmia36lerfcwf2tj5pafdlfbe2na.arweave.net/dY7QHNG5nnbVDrs36Zk1YxAN-WSJRWLqaevAUayhJpo/packages/flags/lib/validate-flags.ts:4:1     

TS1371 [ERROR]: This import is never used as a value and must use 'import type' because the 'importsNotUsedAsValues' is set to 'error'.
import { IFlagArgument, IFlagOptions } from '../../flags/lib/types.ts';
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://owhnahgrxgphnvioxm36tgjvmmia36lerfcwf2tj5pafdlfbe2na.arweave.net/dY7QHNG5nnbVDrs36Zk1YxAN-WSJRWLqaevAUayhJpo/packages/command/types/boolean.ts:1:1        

TS1371 [ERROR]: This import is never used as a value and must use 'import type' because the 'importsNotUsedAsValues' is set to 'error'.
import { IFlagArgument, IFlagOptions } from '../../flags/lib/types.ts';
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://owhnahgrxgphnvioxm36tgjvmmia36lerfcwf2tj5pafdlfbe2na.arweave.net/dY7QHNG5nnbVDrs36Zk1YxAN-WSJRWLqaevAUayhJpo/packages/command/types/number.ts:1:1

TS1371 [ERROR]: This import is never used as a value and must use 'import type' because the 'importsNotUsedAsValues' is set to 'error'.
import { IFlagArgument, IFlagOptions } from '../../flags/lib/types.ts';
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://owhnahgrxgphnvioxm36tgjvmmia36lerfcwf2tj5pafdlfbe2na.arweave.net/dY7QHNG5nnbVDrs36Zk1YxAN-WSJRWLqaevAUayhJpo/packages/command/types/string.ts:1:1

TS1371 [ERROR]: This import is never used as a value and must use 'import type' because the 'importsNotUsedAsValues' is set to 'error'.
import { IArgumentDetails } from './types.ts';
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://owhnahgrxgphnvioxm36tgjvmmia36lerfcwf2tj5pafdlfbe2na.arweave.net/dY7QHNG5nnbVDrs36Zk1YxAN-WSJRWLqaevAUayhJpo/packages/command/lib/arguments-parser.ts:3:1 

TS1371 [ERROR]: This import is never used as a value and must use 'import type' because the 'importsNotUsedAsValues' is set to 'error'.
import { ICell } from './cell.ts';
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://owhnahgrxgphnvioxm36tgjvmmia36lerfcwf2tj5pafdlfbe2na.arweave.net/dY7QHNG5nnbVDrs36Zk1YxAN-WSJRWLqaevAUayhJpo/packages/table/lib/row.ts:1:1

TS1371 [ERROR]: This import is never used as a value and must use 'import type' because the 'importsNotUsedAsValues' is set to 'error'.
import { IFlagOptions } from '../../flags/lib/types.ts';
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://owhnahgrxgphnvioxm36tgjvmmia36lerfcwf2tj5pafdlfbe2na.arweave.net/dY7QHNG5nnbVDrs36Zk1YxAN-WSJRWLqaevAUayhJpo/packages/command/lib/help-generator.ts:2:1   

TS1371 [ERROR]: This import is never used as a value and must use 'import type' because the 'importsNotUsedAsValues' is set to 'error'.
import { Command } from './command.ts';
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://owhnahgrxgphnvioxm36tgjvmmia36lerfcwf2tj5pafdlfbe2na.arweave.net/dY7QHNG5nnbVDrs36Zk1YxAN-WSJRWLqaevAUayhJpo/packages/command/lib/help-generator.ts:6:1   

TS1371 [ERROR]: This import is never used as a value and must use 'import type' because the 'importsNotUsedAsValues' is set to 'error'.
import { IEnvVariable, IExample, IOption } from './types.ts';
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://owhnahgrxgphnvioxm36tgjvmmia36lerfcwf2tj5pafdlfbe2na.arweave.net/dY7QHNG5nnbVDrs36Zk1YxAN-WSJRWLqaevAUayhJpo/packages/command/lib/help-generator.ts:7:1   

TS1371 [ERROR]: This import is never used as a value and must use 'import type' because the 'importsNotUsedAsValues' is set to 'error'.
import { IFlagArgument, IFlagOptions, IFlagsResult, IFlagValue, IFlagValueHandler, IFlagValueType, ITypeHandler } from '../../flags/lib/types.ts';
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://owhnahgrxgphnvioxm36tgjvmmia36lerfcwf2tj5pafdlfbe2na.arweave.net/dY7QHNG5nnbVDrs36Zk1YxAN-WSJRWLqaevAUayhJpo/packages/command/lib/command.ts:5:1

TS1371 [ERROR]: This import is never used as a value and must use 'import type' because the 'importsNotUsedAsValues' is set to 'error'.
    at https://owhnahgrxgphnvioxm36tgjvmmia36lerfcwf2tj5pafdlfbe2na.arweave.net/dY7QHNG5nnbVDrs36Zk1YxAN-WSJRWLqaevAUayhJpo/packages/command/lib/command.ts:14:1

TS1371 [ERROR]: This import is never used as a value and must use 'import type' because the 'importsNotUsedAsValues' is set to 'error'.
import { IFlagArgument, IFlagOptions } from '../../flags/lib/types.ts';
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://owhnahgrxgphnvioxm36tgjvmmia36lerfcwf2tj5pafdlfbe2na.arweave.net/dY7QHNG5nnbVDrs36Zk1YxAN-WSJRWLqaevAUayhJpo/packages/command/types/type.ts:1:1

TS1371 [ERROR]: This import is never used as a value and must use 'import type' because the 'importsNotUsedAsValues' is set to 'error'.
import { Command } from '../lib/command.ts';
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://owhnahgrxgphnvioxm36tgjvmmia36lerfcwf2tj5pafdlfbe2na.arweave.net/dY7QHNG5nnbVDrs36Zk1YxAN-WSJRWLqaevAUayhJpo/packages/command/types/type.ts:2:1

TS1371 [ERROR]: This import is never used as a value and must use 'import type' because the 'importsNotUsedAsValues' is set to 'error'.
import { IFlagArgument, IFlagOptions, ITypeHandler } from '../../flags/lib/types.ts';
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://owhnahgrxgphnvioxm36tgjvmmia36lerfcwf2tj5pafdlfbe2na.arweave.net/dY7QHNG5nnbVDrs36Zk1YxAN-WSJRWLqaevAUayhJpo/packages/command/lib/types.ts:1:1

TS1371 [ERROR]: This import is never used as a value and must use 'import type' because the 'importsNotUsedAsValues' is set to 'error'.
import { Type } from '../types/type.ts';
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://owhnahgrxgphnvioxm36tgjvmmia36lerfcwf2tj5pafdlfbe2na.arweave.net/dY7QHNG5nnbVDrs36Zk1YxAN-WSJRWLqaevAUayhJpo/packages/command/lib/types.ts:2:1

TS1371 [ERROR]: This import is never used as a value and must use 'import type' because the 'importsNotUsedAsValues' is set to 'error'.
import { Command } from './command.ts';
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://owhnahgrxgphnvioxm36tgjvmmia36lerfcwf2tj5pafdlfbe2na.arweave.net/dY7QHNG5nnbVDrs36Zk1YxAN-WSJRWLqaevAUayhJpo/packages/command/lib/types.ts:3:1

TS1371 [ERROR]: This import is never used as a value and must use 'import type' because the 'importsNotUsedAsValues' is set to 'error'.
import { IFlags } from '../../../flags/lib/types.ts';
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://owhnahgrxgphnvioxm36tgjvmmia36lerfcwf2tj5pafdlfbe2na.arweave.net/dY7QHNG5nnbVDrs36Zk1YxAN-WSJRWLqaevAUayhJpo/packages/command/commands/completions/complete.ts:2:1

TS1371 [ERROR]: This import is never used as a value and must use 'import type' because the 'importsNotUsedAsValues' is set to 'error'.
import { ICompleteSettings } from '../../lib/types.ts';
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://owhnahgrxgphnvioxm36tgjvmmia36lerfcwf2tj5pafdlfbe2na.arweave.net/dY7QHNG5nnbVDrs36Zk1YxAN-WSJRWLqaevAUayhJpo/packages/command/commands/completions/complete.ts:4:1

TS1371 [ERROR]: This import is never used as a value and must use 'import type' because the 'importsNotUsedAsValues' is set to 'error'.
import { Command } from './command.ts';
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://owhnahgrxgphnvioxm36tgjvmmia36lerfcwf2tj5pafdlfbe2na.arweave.net/dY7QHNG5nnbVDrs36Zk1YxAN-WSJRWLqaevAUayhJpo/packages/command/lib/zsh-completions-generator.ts:2:1

TS1371 [ERROR]: This import is never used as a value and must use 'import type' because the 'importsNotUsedAsValues' is set to 'error'.
import { IArgumentDetails, IOption } from './types.ts';
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://owhnahgrxgphnvioxm36tgjvmmia36lerfcwf2tj5pafdlfbe2na.arweave.net/dY7QHNG5nnbVDrs36Zk1YxAN-WSJRWLqaevAUayhJpo/packages/command/lib/zsh-completions-generator.ts:3:1

TS1371 [ERROR]: This import is never used as a value and must use 'import type' because the 'importsNotUsedAsValues' is set to 'error'.
import { Command } from '../lib/command.ts';
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://owhnahgrxgphnvioxm36tgjvmmia36lerfcwf2tj5pafdlfbe2na.arweave.net/dY7QHNG5nnbVDrs36Zk1YxAN-WSJRWLqaevAUayhJpo/packages/command/types/command.ts:1:1        

TS1371 [ERROR]: This import is never used as a value and must use 'import type' because the 'importsNotUsedAsValues' is set to 'error'.
import { IFlags } from '../../flags/lib/types.ts';
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://owhnahgrxgphnvioxm36tgjvmmia36lerfcwf2tj5pafdlfbe2na.arweave.net/dY7QHNG5nnbVDrs36Zk1YxAN-WSJRWLqaevAUayhJpo/packages/command/commands/help.ts:1:1        

TS1371 [ERROR]: This import is never used as a value and must use 'import type' because the 'importsNotUsedAsValues' is set to 'error'.
import { Command } from '../lib/command.ts';
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://owhnahgrxgphnvioxm36tgjvmmia36lerfcwf2tj5pafdlfbe2na.arweave.net/dY7QHNG5nnbVDrs36Zk1YxAN-WSJRWLqaevAUayhJpo/packages/command/types/action-list.ts:1:1    

TS1371 [ERROR]: This import is never used as a value and must use 'import type' because the 'importsNotUsedAsValues' is set to 'error'.
import { Command } from '../lib/command.ts';
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://owhnahgrxgphnvioxm36tgjvmmia36lerfcwf2tj5pafdlfbe2na.arweave.net/dY7QHNG5nnbVDrs36Zk1YxAN-WSJRWLqaevAUayhJpo/packages/command/types/child-command.ts:1:1  

TS1371 [ERROR]: This import is never used as a value and must use 'import type' because the 'importsNotUsedAsValues' is set to 'error'.
import { KeyEvent } from '../../keycode/lib/key-event.ts';
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://owhnahgrxgphnvioxm36tgjvmmia36lerfcwf2tj5pafdlfbe2na.arweave.net/dY7QHNG5nnbVDrs36Zk1YxAN-WSJRWLqaevAUayhJpo/packages/prompt/lib/generic-prompt.ts:4:1    

TS1371 [ERROR]: This import is never used as a value and must use 'import type' because the 'importsNotUsedAsValues' is set to 'error'.
import { KeyEvent } from '../../keycode/lib/key-event.ts';
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://owhnahgrxgphnvioxm36tgjvmmia36lerfcwf2tj5pafdlfbe2na.arweave.net/dY7QHNG5nnbVDrs36Zk1YxAN-WSJRWLqaevAUayhJpo/packages/prompt/lib/generic-input.ts:3:1     

TS1371 [ERROR]: This import is never used as a value and must use 'import type' because the 'importsNotUsedAsValues' is set to 'error'.
import { KeyEvent } from '../../keycode/mod.ts';
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://owhnahgrxgphnvioxm36tgjvmmia36lerfcwf2tj5pafdlfbe2na.arweave.net/dY7QHNG5nnbVDrs36Zk1YxAN-WSJRWLqaevAUayhJpo/packages/prompt/prompts/checkbox.ts:2:1      

TS1371 [ERROR]: This import is never used as a value and must use 'import type' because the 'importsNotUsedAsValues' is set to 'error'.
import { KeyEvent } from '../../keycode/lib/key-event.ts';
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://owhnahgrxgphnvioxm36tgjvmmia36lerfcwf2tj5pafdlfbe2na.arweave.net/dY7QHNG5nnbVDrs36Zk1YxAN-WSJRWLqaevAUayhJpo/packages/prompt/prompts/number.ts:2:1        

TS1371 [ERROR]: This import is never used as a value and must use 'import type' because the 'importsNotUsedAsValues' is set to 'error'.
import { KeyEvent } from '../../keycode/lib/key-event.ts';
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://owhnahgrxgphnvioxm36tgjvmmia36lerfcwf2tj5pafdlfbe2na.arweave.net/dY7QHNG5nnbVDrs36Zk1YxAN-WSJRWLqaevAUayhJpo/packages/prompt/prompts/select.ts:2:1        

TS1371 [ERROR]: This import is never used as a value and must use 'import type' because the 'importsNotUsedAsValues' is set to 'error'.
import { KeyEvent } from '../../keycode/lib/key-event.ts';
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://owhnahgrxgphnvioxm36tgjvmmia36lerfcwf2tj5pafdlfbe2na.arweave.net/dY7QHNG5nnbVDrs36Zk1YxAN-WSJRWLqaevAUayhJpo/packages/prompt/prompts/toggle.ts:2:1        

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
  LevelName,
  ~~~~~~~~~
    at https://nulzkufawsbf6nxyk7vfekrhs43qldcnbc64rdo7nq2ojnl74rza.arweave.net/bReVUKC0gl82-FfqUionlzcFjE0IvciN32w05LV_5HI/deps.ts:25:3

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
  IFlagArgument,
  ~~~~~~~~~~~~~
    at https://nulzkufawsbf6nxyk7vfekrhs43qldcnbc64rdo7nq2ojnl74rza.arweave.net/bReVUKC0gl82-FfqUionlzcFjE0IvciN32w05LV_5HI/deps.ts:68:3

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
  IFlagOptions,
  ~~~~~~~~~~~~
    at https://nulzkufawsbf6nxyk7vfekrhs43qldcnbc64rdo7nq2ojnl74rza.arweave.net/bReVUKC0gl82-FfqUionlzcFjE0IvciN32w05LV_5HI/deps.ts:69:3

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
  GlobalModuleConfig,
  ~~~~~~~~~~~~~~~~~~
    at https://nulzkufawsbf6nxyk7vfekrhs43qldcnbc64rdo7nq2ojnl74rza.arweave.net/bReVUKC0gl82-FfqUionlzcFjE0IvciN32w05LV_5HI/deps.ts:82:3

TS1371 [ERROR]: This import is never used as a value and must use 'import type' because the 'importsNotUsedAsValues' is set to 'error'.
import { DefaultOptions } from "../commands.ts";
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://nulzkufawsbf6nxyk7vfekrhs43qldcnbc64rdo7nq2ojnl74rza.arweave.net/bReVUKC0gl82-FfqUionlzcFjE0IvciN32w05LV_5HI/src/commands/link.ts:2:1

TS1371 [ERROR]: This import is never used as a value and must use 'import type' because the 'importsNotUsedAsValues' is set to 'error'.
import { DefaultOptions } from "../commands.ts";
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://nulzkufawsbf6nxyk7vfekrhs43qldcnbc64rdo7nq2ojnl74rza.arweave.net/bReVUKC0gl82-FfqUionlzcFjE0IvciN32w05LV_5HI/src/commands/init.ts:18:1

TS1371 [ERROR]: This import is never used as a value and must use 'import type' because the 'importsNotUsedAsValues' is set to 'error'.
import { DefaultOptions } from "../commands.ts";
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://nulzkufawsbf6nxyk7vfekrhs43qldcnbc64rdo7nq2ojnl74rza.arweave.net/bReVUKC0gl82-FfqUionlzcFjE0IvciN32w05LV_5HI/src/commands/publish.ts:17:1

import { Ignore } from "../context/ignore.ts";
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://nulzkufawsbf6nxyk7vfekrhs43qldcnbc64rdo7nq2ojnl74rza.arweave.net/bReVUKC0gl82-FfqUionlzcFjE0IvciN32w05LV_5HI/src/commands/publish.ts:24:1

TS1371 [ERROR]: This import is never used as a value and must use 'import type' because the 'importsNotUsedAsValues' is set to 'error'.
import { DefaultOptions } from "../commands.ts";
    at https://nulzkufawsbf6nxyk7vfekrhs43qldcnbc64rdo7nq2ojnl74rza.arweave.net/bReVUKC0gl82-FfqUionlzcFjE0IvciN32w05LV_5HI/src/commands/update.ts:14:1

TS1371 [ERROR]: This import is never used as a value and must use 'import type' because the 'importsNotUsedAsValues' is set to 'error'.
import { DefaultOptions } from "../commands.ts";
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://nulzkufawsbf6nxyk7vfekrhs43qldcnbc64rdo7nq2ojnl74rza.arweave.net/bReVUKC0gl82-FfqUionlzcFjE0IvciN32w05LV_5HI/src/commands/install.ts:15:1

TS1371 [ERROR]: This import is never used as a value and must use 'import type' because the 'importsNotUsedAsValues' is set to 'error'.
import { DefaultOptions } from "../commands.ts";
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

TS1371 [ERROR]: This import is never used as a value and must use 'import type' because the 'importsNotUsedAsValues' is set to 'error'.
import { DefaultOptions } from "./src/commands.ts";
    at https://nulzkufawsbf6nxyk7vfekrhs43qldcnbc64rdo7nq2ojnl74rza.arweave.net/bReVUKC0gl82-FfqUionlzcFjE0IvciN32w05LV_5HI/mod.ts:2:1

Found 48 errors.
```

I then tried to upgrade with `eggs upgrade` to see if there was a fix but `eggs upgrade` produced the same errors. I then installed the latest version (which was actually the same version I was on previously) with `deno install -A -f --unstable -n eggs https://x.nest.land/eggs@0.2.1/mod.ts` and Deno said that it had "`✅ Successfully installed eggs`". However, now I wouldn't get anything when I ran an `eggs` command (not even an error message). The commands run but do nothing.

**To Reproduce**

I think that this is a problem with Deno 1.4, although I can't be sure as I am having trouble downgrading version.

**Expected behavior**

The commands should run without errors and output logs of what is happening to the console.

**Desktop:**
 - OS: Windows 10
 - nest.land Version: 0.2.1

**Comment by TTtie** [comment]
This is caused by the new default TS configuration in unstable Deno 1.4.0:  
denoland/deno#7327
denoland/deno#7413

**Comment by SteelAlloy** [comment]
I'll work on this asap

**Comment by t8** [comment]
Thanks for making this issue, @TheWizardBear, and thanks for the incredibly quick patch, @oganexon!
